---
title: "Soil Profile Data Mining and Statistical Analysis"
author: "Kar"
date: '2022-07'
output:
  github_document:
    toc: yes
    toc_depth: 4
    number_sections: yes
always_allow_html: yes
---

***

***

# R PACKAGES

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(car)
library(kableExtra)
library(cowplot)


```


# DATA PREPARATION

## Data Import

Randomly sample 10 rows of data from the table

```{r}
sample_n(Soils, 10)

```

## Data Description

```{r}
Variables <- names(Soils)

Description <- c("a factor with 12 levels, corresponding to the combinations of Contour and Depth",
                 "a factor with 3 levels: Depression Slope Top",
                 "a factor with 4 levels: 0-10 10-30 30-60 60-90",
                 "a factor with 12 levels, giving abbreviations for the groups: D0 D1 D3 D6 S0 S1 S3 S6 T0 T1 T3 T6",
                 "a factor with levels 1 2 3 4",
                 "soil pH",
                 "total nitrogen in %",
                 "bulk density in gm/cm$^3$",
                 "total phosphorous in ppm",
                 "calcium in me/100 gm.",
                 "magnesium in me/100 gm.",
                 "phosphorous in me/100 gm.",
                 "sodium in me/100 gm.",
                 "conductivity Details")

data.frame(Variables, Description) %>% 
  kbl() %>%
  kable_styling(bootstrap_options = c("bordered", "stripped", "hover"), full_width = F)
  

```

## Data Exploration

* This is a small data set with 48 rows of data and 14 variables. 
* There are 4 factor variables which are "Group", "Contour", "Depth", "Gp", and "Block".  
* There are 9 numerical variables which are "pH",  "N",  "Dens",  "P",  "Ca",  "Mg",  "K",  "Na", and "Conduc".  

```{r}
glimpse(Soils)

```
There is no missing value in the data set. 

```{r}
colSums(is.na(Soils))
```

```{r}
summary(Soils, maxsum = 12)

```



